project:
  type: website

website:
  title: "antiKlexos"
  image: "4-blue-sm.png"
  favicon: "4-blue-fav.png"

  navbar:
    
    logo: "4-blue-sm.png"
    logo-alt: "antiKlexos logo."
    title: false
    collapse-below: lg
    right:
      - href: about.qmd
        text: "Manifesto"
      - href: posts.qmd
        text: "Posts"
format:
  html:
    theme: 
      light: cosmo
     
    css: styles.css
    toc: true



